### ISSUE TITLE
Styles overridden

### ISSUE THREAD

**Issue by greyivy** [niftylettuce/preview-email#3]
It seems the styles in my HTML emails are being overridden by those of preview-email. Am I missing something?

Thanks for the great project!

**Comment by IsFlwrs** [comment]
Hi!
Can you upload a screenshot with the result?

I had a similar problem, the **preview-email** did not render the css style when I had this line:
`<link href="style.css" rel="stylesheet">`

With my library render [EJS](http://ejs.co/) I have included the css inside of my html file:
`<style>
  <%- include('style.css'); %>
</style>`

**Comment by IsFlwrs** [comment]
Hi!
Can you upload a screenshot with the result?

I had a similar problem, the **preview-email** did not render the css style when I had this line:
`<link href="style.css" rel="stylesheet">`

With my library render [EJS](http://ejs.co/) in order to solve the problem I have included the css inside of my html file:
`<style>
  <%- include('style.css'); %>
</style>`

**Comment by niftylettuce** [comment]
@greyivy they shouldn't be overridden because it's using a seamless iframe

@IsFlwrs I think the problem is that the reference is not correct, the path does not exist.  you can debug with `DEBUG=email-templates node app.js`

https://github.com/niftylettuce/email-templates#debugging
