### ISSUE TITLE
Doesn't show on Ubuntu?

### ISSUE THREAD

**Issue by sittingbool** [niftylettuce/preview-email#5]
Hi, 
first of all great work! We are using your email-templates module and the preview shows on every system except Ubuntu using Chrome.
Is that just us or a general issue?
All the best

**Comment by superhawk610** [comment]
Can confirm, I'm noticing the same behavior. Interestingly, VS Code opens a new window instead...?

**Comment by niftylettuce** [comment]
@sittingbool @superhawk610 are you using Gnome 3.30? see <https://github.com/sindresorhus/opn/issues/104> (`opn` is the underlying package we use).  also see <https://unix.stackexchange.com/a/101381>.

I'm guessing something is happening with `xdg-open` that's causing it to fail on your system.

If you discover a solution or what the problem is please let us know or post issue here and at https://github.com/sindresorhus/opn

**Comment by sittingbool** [comment]
It's a fresh and standard Ubuntu 16.04. It works with the standard browser but if you make Chrome your standard browser not anymore.

**Comment by niftylettuce** [comment]
Please try `email-templates@5.0.3` which uses `preview-email@0.0.10`.  I've just published both packages to NPM.  Documentation is provided at the link below which should hopefully help you resolve your OS-specific issue.  Let me know if you have any issues.

Docs: https://github.com/niftylettuce/email-templates#open-email-previews-in-firefox
