### ISSUE TITLE
Would be amazing to be able to change the template design as a option.

### ISSUE THREAD

**Issue by madshensel** [niftylettuce/preview-email#6]
I would like to make a template for the preview or at least be able to update the styling of if ex. link to a stylesheet.

**Comment by niftylettuce** [comment]
@madshensel I've released v1.0.0 which adds support for custom templates.  See the updated README example here <https://github.com/niftylettuce/preview-email#custom-preview-template-and-stylesheets>.

Also note that I will be releasing a new version of `email-templates` shortly as well that includes this new setup and API.  This was a breaking change because I cleaned up the options, it's now `previewEmail(message, options)`.

Let me know if you have any issues, and if you make a cool template/styling for the preview we'll gladly accept a PR for some type of "theme" selection.

**Comment by niftylettuce** [comment]
Note that v1.0.0 was just unpublished because I dropped support for Node v6 and did not include that as a change.  I just now released v1.0.1.

https://github.com/niftylettuce/preview-email/releases/tag/v1.0.1

**Comment by niftylettuce** [comment]
A new version of `email-templates` was released with a bumped version of `preview-email`, which now allows you to have custom templates/stylesheets in that package as well.

See https://github.com/niftylettuce/email-templates/releases/tag/v6.0.0
